### ISSUE TITLE
purchase history a better metric than current price

### ISSUE THREAD

**Issue by jatx50** [zbee/xiv-sealgil#1]
Firstly, great work. I was looking at building something similar to this but you've already done it.

First thing I did was see what GC material is selling for the most on Omega (my world), and it currently shows... Spine Drops at 80,769,230! Of course no one has actually paid that. Have you considered using purchase history rather than current asking price to avoid this sort of thing?

**Comment by zbee** [comment]
Ah! That's very sensible, seems so obvious - I will add that in; I needed to tweak the maths anyway.

**Comment by zbee** [comment]
I'll have to play with the math more - I'll use whichever is lower if there's a disparity, I encountered some outliers there. I'll get that in tonight.
